# application.properties

spring.application.name=demotest
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# === Server port (optional) ===
server.port=8080

# PostgreSQL DB config
# here postgres is database name and it can be changed . Eg:testdb
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# here postgres is a username and it can be changed to anything
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA/Hibernate config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


